apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./db.yaml
  - ./pvc.yaml
  - ./front.yaml
  - ./imageUpdater.yaml
  - ./ingress.yaml
  - ./harbor.yaml
  - ./secrets.yaml
  - ./2025-deploy.yaml
  - ./2025-service.yaml
  - ./adminer.yaml
